### ISSUE TITLE
Zabbix-Agent - service not found

### ISSUE THREAD

**Issue by jerry3k** [clearlinux/distribution#1784]
Adding the zabbix-agent bundle doesn't add any /etc/zabbix folder, also running 'systemctl start zabbix-agent' returns 'Failed to start zabbix-agent.service: Unit zabbix-agent.service not found.'

**Comment by ahkok** [comment]
> Adding the zabbix-agent bundle doesn't add any /etc/zabbix folder

that's normal. In ClearLinux OS, we do NOT create folders in `/etc/` for any package - ever. We expect, and try to, make services work completely out of the box, as much as possible.

**Comment by ahkok** [comment]
Upstream doesn't create a zabbix-agent.service, unfortunately. hmmmm.

**Comment by jerry3k** [comment]
Is this something it's meant to do or a bug?

Dr. Jeremy Murray
Co-Founder & CTO
Aceso AS (www.aceso.no)<http://www.aceso.no)>
Oslo - London - Edinburgh


CONFIDENTIALITY NOTICE
This message is confidential and intended solely for the person(s) to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient(s), you must not read, copy, distribute, discuss or take any action in reliance on it. If you have received this information in error, please notify Aceso AS as soon as possible on the above telephone number or by return email.

________________________________

**Comment by ahkok** [comment]
> Is this something it's meant to do or a bug?

The year is `2020`, so yes, really, upstream should create proper default systemd unit files. Most projects to, there's just a lot of resistance in many projects in doing this. This means every distro needs to figure out their own units, and, as a consequence, things may be running insecure. Obviously the zabbix folks are the experts, so they should provide these with sane and secure default values. (end soapbox).

**Comment by ahkok** [comment]
Ok, I took some time to take this one step beyond. It still doesn't make either the agent or the server start by default, though! But that's because either fall into the category of services that this is not reasonable because these need to be configured explicitly to connect to a machine on the network(the agent), or open ports and database connections (the server). It is not reasonable to ship these with invalid configs.

However, I've done the following:
- Added zabbix-agent.service and zabbix-server.service
- Added `zabbix` user for the agent, so it doesn't run as root
- Added `Include` configs so that you should be able to be on your way by creating either `/etc/zabbix_server.conf.d/local.conf` or something (for the server) or create `/etc/zabbix/zabbix_agentd.conf` (for the agent) with just the few bits needed.
- update to 4.4.5

For reference, the template files are here:

https://github.com/zabbix/zabbix/tree/master/conf

This update should be out in 1-2 business days. I'll try and make time to see if I can do a test deployment myself to make sure it's not too complex to set this up after that. In the mean time - feel free to comment in here and report back in a few days with feedback.

**Comment by ahkok** [comment]
Note one problem of zabbix config files is that they explicitly state that `Include` can not be used to "overlay" system default configuration files. We can't do something like
`Listen 127.0.0.1`
and then later `Include` another file that has:
`Listen 0.0.0.0`.

**Comment by ahkok** [comment]
Added `zabbix` user IDs, and added SQL database templates. Setup of the server is still a manual thing as you can run the server against mariadb, sqlite, etc. This is unlikely to ever change.
