### ISSUE TITLE
Firefox - gdk-pixbuf error

### ISSUE THREAD

**Issue by rbharathkumar** [clearlinux/distribution#414]
Firefox - Issues in Plasma Desktop
I have currently installed the plasma desktop and have it up to date.
As per suggestion from @anselmolsm I am creating a separate Issue for tracking purposes.

Steps to Reproduce:
1. Install the firefox bundle.
2. Start firefox through the command line.

Issue:
1. Multiple warnings. Note that these warnings occur only when no firefox instances are running. If we have one instance running and start another, these warnings do not appear.

```
(firefox:2862): GdkPixbuf-WARNING **: 10:13:30.995: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.

(firefox:2862): GdkPixbuf-WARNING **: 10:13:30.995: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```

2. When the default toolbar is removed using the customize option, the controls on the right corner disappear. This means the minimize, maximize and close buttons.

Note that the buttons are still there and clickable. Just not visible. I googled and was getting some errors regarding client side decorations not properly getting set.

**Comment by phmccarty** [comment]
Closing as duplicate of #381

**Comment by anselmolsm** [comment]
Renamed and reopened as it does not seem necessarily related to KDE/Plasma.

**Comment by rbharathkumar** [comment]
Thank you for response/action. I would suggest that this issue remain open since it also has reference to 1. The rendering of Non-English characters by Firefox 
2. The appearance of the minimize and maximize buttons.. 
Also as referenced by @anselmolsm it may not be related to plasma desktop...so

**Comment by mrkz** [comment]
@rbharathkumar  please verify
> 1. The rendering of Non-English characters by Firefox

is fixed, as a change was introduced which should solve this particular issue.

**Comment by rbharathkumar** [comment]
Hi @mrkz Thank you for your response.
It indeed solved the issue with the language rendering.
![image](https://user-images.githubusercontent.com/38585383/53064813-2723da80-34ef-11e9-9049-42ad26de92e8.png)

I also noticed that the pixbuf errors are not present anymore, but the other issue of the missing minimize/maximize/close button still exists. I mean the buttons are there and clickable but not visible.
Also from the console I get the below message.

```
rbkclear@clearlinuxkde ~ $ firefox

(firefox:722): Gtk-WARNING **: 09:04:58.829: Could not find the icon 'window-minimize-symbolic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

```
Great progress nevertheless..
Appreciate it...
Will wait for the other fixes as well.
Thank you.

**Comment by mrkz** [comment]
> Hi @mrkz Thank you for your response.
> It indeed solved the issue with the language rendering.
> ![image](https://user-images.githubusercontent.com/38585383/53064813-2723da80-34ef-11e9-9049-42ad26de92e8.png)
> 
> I also noticed that the pixbuf errors are not present anymore, [...]

I'm closing this issue as the main issues noticed here have been addressed.

> rbkclear@clearlinuxkde ~ $ firefox
> 
> (firefox:722): Gtk-WARNING **: 09:04:58.829: Could not find the icon 'window-minimize-symbolic'. The 'hicolor' theme
> was not found either, perhaps you need to install it.
> You can get a copy from:
>         http://icon-theme.freedesktop.org/releases

I'm not able to reproduce this error (CLR release 27790). if you still notice this bug around, please do open a new issue with more details (CLR release, installed bundles, etc).

Thanks for your reports!

**Comment by rbharathkumar** [comment]
Thank you for your response...
I am currently on 27970...Update to 28070 is currently downloading and upon install, will validate...if the issue persists, will open a new issue with the details you had requested...
Thank you once again.
