### ISSUE TITLE
29030 breaks wpa_supplicant (following upgrade from 2.7->2.8)

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#640]
**Describe the bug**
wpa_supplicant fails to start following swupd to 29030 (which included an update to wpa_supplicant from 2.7 -> 2.8)

Looks like this commit @fenrus75 breaks the dbus rules?

https://github.com/clearlinux-pkgs/wpa_supplicant/commit/72bdb9570b1262943ae0cebbb643388e3edd459f#diff-48da396c22dec74d0a43b9ca243a0547

Before update :-

```
dbus-daemon[]: [system] Activating via systemd: service name='fi.w1.wpa_supplicant1' unit='wpa_supplicant.service' requested by ':1.2' (uid=0 pid=551 comm="/usr/bin/NetworkManager --no-daemon ")
dbus-daemon[]: [system] Successfully activated service 'fi.w1.wpa_supplicant1'
wpa_supplicant[]: Successfully initialized wpa_supplicant
```

After update
```
wpa_supplicant[]: dbus: Could not request service name: org.freedesktop.DBus.Error.AccessDenied Connection ":1.834" is not allowed to own the service "fi.w1.wpa_supplicant1" due to security policies in the configuration file
wpa_supplicant[]: Failed to initialize wpa_supplicant
wpa_supplicant[]: dbus: Could not request service name: org.freedesktop.DBus.Error.AccessDenied Connection ":1.1052" is not allowed to own the service "fi.w1.wpa_supplicant1" due to security policies in the configuration file
wpa_supplicant[]: Failed to initialize wpa_supplicant
```

**Comment by mrkz** [comment]
We did integrate `wpa_supplicant.service` (and its D-Bus integration) for `conman` (which I believe we're no longer shipping), so this change would make sense if @fenrus75 meant to remove this conman leftover, as the removal did not include the `wpa_supplicant.service` unit file this error is appearing.

This is what I could grasp form a quick look, perhaps @fenrus75  could shed some light here.

@xlfe does this issue prevents you from using Networking on your end or this is just a harmless issue you noticed?

Understanding better the use-case required will help us to determine the best route to follow.

**Comment by Mountainerd** [comment]
My wireless networking is completely offline and I don't have access to hardwire to confirm if it's the entire stack.

**Comment by mrkz** [comment]
@Mountainerd Thanks for the confirmation, I'm looking at bringing back D-Bus integration of `wpa_supplicant`.

I'll comment back once the fix is available.

**Comment by mrkz** [comment]
@xlfe @Mountainerd 29050 should have wpa_supplicant back to a working state.

As a workaround (in the meantime), please make sure the following files exists:
```
 % cat /usr/share/dbus-1/system-services/fi.w1.wpa_supplicant1.service
[D-BUS Service]
Name=fi.w1.wpa_supplicant1
Exec=/usr/bin//wpa_supplicant -u
User=root
SystemdService=wpa_supplicant.service

 % cat /usr/share/dbus-1/system.d/wpa_supplicant.conf
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
        <policy user="root">
                <allow own="fi.w1.wpa_supplicant1"/>

                <allow send_destination="fi.w1.wpa_supplicant1"/>
                <allow send_interface="fi.w1.wpa_supplicant1"/>
                <allow receive_sender="fi.w1.wpa_supplicant1" receive_type="signal"/>
        </policy>
        <policy context="default">
                <deny own="fi.w1.wpa_supplicant1"/>
                <deny send_destination="fi.w1.wpa_supplicant1"/>
                <deny receive_sender="fi.w1.wpa_supplicant1" receive_type="signal"/>
        </policy>
</busconfig>
 %  
```

Having those files should let `wpa_supplicant` to start again without issues

**Comment by rustylynch** [comment]
FYI I am also seeing this problem on 29040 and for me the above to files are missing.  I created both as directed above and now my wireless is working correctly again.

**Comment by Mountainerd** [comment]
@mrkz Thank you for the quick turnaround on this. I still don't see 29050 available so I'll try creating the files and restarting.

**Comment by Mountainerd** [comment]
@mrkz So, on a different system experiencing the same issue, I did a `swupd verify -f --picky -m 29050` (I know, I know ... probably not be advised since it wasn't showing up when checking with `swupd check-update`). But it did fix my wireless issues.

**Comment by xlfe** [comment]
> @xlfe does this issue prevents you from using Networking on your end or this is just a harmless issue you noticed?

Yes - it did. Ethernet worked, but wifi nada because wpa_supplicant wouldn't start...

Just upgraded to 29050 and I can see wpa_supplicant has been reverted to 2.7 which immediately fixed wifi connectivity for me.

thanks @mrkz

**Comment by mrkz** [comment]
> Just upgraded to 29050 and I can see wpa_supplicant has been reverted to 2.7 which immediately fixed wifi connectivity for me.

@xlfe Please notice that we're still updating back to `wpa_supplicant-2.8`(for release **29060** or later), but I verified we're not screwing things up again.

>will those files need to be removed when 29050 hits my system or is manually creating the files doing what 29050 does?

@Mountainerd regarding the files created, yes **29050** brings those files back. Swupd will handle them gracefully afterwards (e.g: if you ever edit something on `/usr` (except `/usr/local/`) swupd will fix those files on update (or `verify --fix`), so in summary you shouldn't worry about it because swupd will own them once we add them back as part of the bundle changes (which we just did for **29050** as you mentioned).

This is because of stateless, which I invite you to read more at our [Stateless feature page](https://clearlinux.org/features/stateless) if you're interested.
