### ISSUE TITLE
Cannot start clear linux after installation

### ISSUE THREAD

**Issue by jaycenet** [clearlinux/distribution#808]
Hello,

i cannot start directly ClearLinux after the installation process.
I have to follow this doc : https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl to add an entry in my computer.

But after that i cannot boot, i have this message:
![IMG_20190526_200401](https://user-images.githubusercontent.com/6877004/58385582-bbbc3e00-7ff2-11e9-8769-cb1acc38d73e.jpg)

The boot is working in EFI with the Solus distribution.

Can you help me ?

Thanks

**Comment by x451818** [comment]
Same issue here. The EFI partition contains the following.

├── EFI
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   ├── org.clearlinux
│   │   ├── bootloaderx64.efi
│   │   ├── kernel-org.clearlinux.native.5.0.18-767
│   │   └── loaderx64.efi
│   └── systemd
│       └── systemd-bootx64.efi
└── loader
    ├── entries
    │   └── Clear-linux-native-5.0.18-767.conf
    └── loader.conf

**Comment by bryteise** [comment]
Would you mind showing me a lsblk -f of your system?

**Comment by jaycenet** [comment]
sdb                                                                     
├─sdb1
│    vfat   boot  B47A-FC2C                                             
├─sdb2
│    swap   swap  ff67cb3c-b94a-4ac2-a2f7-b5c214a4ca46                  
└─sdb3
     ext4   root  c29a137b-79d1-446f-b90f-3870d72cd246                  

It's now on disk2 sdb but i have the same problem when the disk is alone on sda

**Comment by alexhultman** [comment]
My "bios" did not list my HDD as a bootable option after installation. The OS ran perfectly fine **from USB stick** and installed, but after installed I could not boot from HDD. Simply no option to. No nothing at all.

I then ran the steps in https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl and **now it boots perfectly fine from HDD**.

This is for my 8-ish year old laptop Asus N56VZ.

Btw, performance tests on Clear Linux are incredibly satisfying!

**Comment by Luraktinus** [comment]
Would be nice if https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl would stll exist SO I CAN BOOT

**Comment by Luraktinus** [comment]
and please add an entry at install

**Comment by mdhorn** [comment]
@Luraktinus  problem was resolved by updating the BIOS on the motherboard.

**Comment by alexhultman** [comment]
http://web.archive.org/web/20190602071311/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl

# Boot with USB sick after install

fdisk -l

# Mount the EFI partition, such as

mount /dev/sda3 /mnt

# Repair

bootctl install --path /mnt

# Unmount

umount /mnt

# Reboot

Do it

**Comment by cbdejavu** [comment]
I'm having the same issue.  New system.  During install told it to destroy the HDD and partition it.  I have tried the above process depicted here:

https://web.archive.org/web/20190602071311/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl

This doesn't fix the issue either.  It seems to work fine without any errors but then doesn't boot.  I have the bios setup to perform a UEFI boot only.  Although AUTO has the same results.

The onscreen error message I'm getting is:

Error 1962: No operating system found.  Press any key to repeat the boot sequence.

I updated the system bios to the latest version as well.

The system is a Lenovo ThinkCentre M91p - Bios Revision 9HKT58AUS
It is running an intel i5-2400 cpu @3.10GHz
4gb ram
4 CPU Cores
Integrated Intel Video.

**Comment by bwarden** [comment]
> I'm having the same issue. New system. During install told it to destroy the HDD and partition it. I have tried the above process depicted here:

@cbdejavu this is a different problem -- please open a new issue.

**Comment by sincorchetes** [comment]
> http://web.archive.org/web/20190602071311/https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot/multi-boot-restore-bl
> 
> # Boot with USB sick after install
> fdisk -l
> 
> # Mount the EFI partition, such as
> mount /dev/sda3 /mnt
> 
> # Repair
> bootctl install --path /mnt
> 
> # Unmount
> umount /mnt
> 
> # Reboot
> Do it

I got this issue tonight with the latest version. I solved this.
